### ISSUE TITLE
Error API Call blocked for Keep-Alive seconds

### ISSUE THREAD

**Issue by Comawhite54** [Vital91/node-red-contrib-ecowatt#1]
I followed the steps but cannot succeed.
The function in node red return this message 
I tried to wait 60 minutes between calls, but same issue.
Is this addon still working ?

"Error API Call blocked for Keep-Alive seconds"

**Comment by Vital91** [comment]
Hello,

2 things, the Enedis API as changed to V5, I will change this but it looks like the new API doesn't work like the previous version, I will investigate.

**Comment by Vital91** [comment]
Hi,

API call updated to V5, please upgrade your Node into Node-Red, ping me if you have issues.

**Comment by Vital91** [comment]
Closed

**Comment by Vital91** [comment]
Hello,
Ecowatt node is now updated to V5 of RTE's API , keep me post if you have
any issues.
You must uninstall the node, update your palet list and install again.

Best regards

Vital

Le lun. 28 oct. 2024 à 14:25, Comawhite54 ***@***.***> a
écrit :
